#!/bin/bash

PROJECT_NAME="~/project"
LOCAL_SHAS=$(find . -type f | xargs git hash-object | sort)

if [[ "$1" == "server" ]]; then
  COMMAND="${@:2}"
  SERVER_SUMS=$(ssh -i ~/Dropbox/glamp-misc.pem ubuntu@ec2-23-22-234-77.compute-1.amazonaws.com "find ${PROJECT_NAME} -type f | xargs git hash-object | sort")

  echo "${LOCAL_SHAS}"
  echo " vs "
  echo "${SERVER_SUMS}"
  if [[ "${LOCAL_SHAS}" != "${SERVER_SHAS}" ]]; then
    echo "syncing"
    scp -q -i ~/Dropbox/glamp-misc.pem -r . ubuntu@ec2-23-22-234-77.compute-1.amazonaws.com:${PROJECT_NAME}
  fi
  ssh -i ~/Dropbox/glamp-misc.pem ubuntu@ec2-23-22-234-77.compute-1.amazonaws.com "
    cd ${PROJECT_NAME}
    "${COMMAND}"
  "
else
  exec "$@"
fi
