#!/usr/bin/env python
import os
import sys

from colorama import init
from colorama import Fore, Back, Style
from prettytable import PrettyTable

import project
import credentials

init()

PROJECT_DIR = os.path.join(os.environ['HOME'], ".yhat/templates")


def prompt_user():
    if os.path.isdir(PROJECT_DIR):
        choices = [f[:-5] for f in os.listdir(PROJECT_DIR) if f.endswith(".json")]
    else:
        choices = []

    choices.append('*new project*')
    choices.append('*download template*')

    choices_lookup = {}
    print "" + Fore.CYAN
    table = PrettyTable([Fore.CYAN + "", Fore.CYAN + "Template"])
    for i, choice in enumerate(choices):
        choices_lookup[str(i+1)] = choice
        table.add_row([
            Fore.CYAN + "(%d)" % (i+1),
            Fore.CYAN + choice
        ])
    print table
    return choices_lookup.get(raw_input("(?) "))


if __name__=="__main__":
    if sys.argv[1]=="new":
        result = prompt_user()
        while result is None:
            result = prompt_user()

        print Fore.GREEN + result
        project.setup(result, result)
    elif sys.argv[1]=="config":
        if len(sys.argv) > 2:
            if sys.argv[2]=="reset":
                credentials.setup()
        else:
            table = PrettyTable(["Key", "Value"])
            for key, value in credentials.read().items():
                table.add_row([key, value])
            print table

