#!/usr/bin/env python
from colorama import init
from colorama import Fore, Back, Style
from prettytable import PrettyTable
import project
import credentials
import os
import sys

init()

PROJECT_DIR = os.path.join(os.environ['HOME'], ".yhat/templates")


def prompt_user():
    # inputs = [
    #     {"prompt": "Project Name: ", "variable": "name"},
    #     {"prompt": "Description: ", "variable": "description"},
    #     {"prompt": "GitHub username: ", "variable": "github_username"},
    #     {"prompt": "Your name: ", "variable": "your_name"},
    #     {"prompt": "Your email: ", "variable": "your_email"}
    # ]

    # user_input = {}
    # for prompt in inputs:
    #     user_input[prompt['variable']] = raw_input(Fore.CYAN + prompt['prompt'])

    # return user_input


    if os.path.isdir(PROJECT_DIR):
        choices = [f[:-5] for f in os.listdir(PROJECT_DIR) if f.endswith(".json")]
    else:
        choices = []

    choices.append('*new project*')
    choices.append('*download template*')

    print Fore.CYAN + "Templates".center(40)
    print Fore.CYAN + "="*40
    choices_lookup = {}
    for i, choice in enumerate(choices):
        print Fore.CYAN + " (%d) %s" % (i+1, choice.ljust(40))
        choices_lookup[str(i+1)] = choice
    return choices_lookup.get(raw_input("(?) "))


if __name__=="__main__":
    if sys.argv[1]=="new":
        result = prompt_user()
        while result is None:
            result = prompt_user()

        print Fore.GREEN + result
        project.setup(result, result)
    elif sys.argv[1]=="config":
        if len(sys.argv) > 2:
            if sys.argv[2]=="reset":
                credentials.setup()
        else:
            table = PrettyTable(["Key", "Value"])
            for key, value in credentials.read().items():
                # print Fore.CYAN + key.ljust(8), ":", value
                table.add_row([key, value])
            print table

